name: Build Flask API to EXE

on:
  push:
    branches:
      - main  # "main" branch'e push yapıldığında çalışır
  workflow_dispatch:  # Manuel olarak da çalıştırabilirsin

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Kur
        run: |
          pip install pyinstaller flask requests

      - name: PyInstaller ile EXE Üret
        run: pyinstaller --onefile --name=LinksAPI app.py

      - name: Çıktıyı Upload Et (GitHub Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: LinksAPI-Executable
          path: dist/LinksAPI.exe

      - name: Versiyon Tag'ı Oluştur
        id: tag_version
        run: |
          git fetch --tags
          TAG="v1.0.$(date +%s)"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG

      - name: GitHub Releases'e Yükle
        uses: softprops/action-gh-release@v1
        with:
          files: dist/LinksAPI.exe
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
